## Agregar etiquetas nutricionales a las comidas

***Propósito de aprendizaje*** En este caso se aprenderá como crear funciones en python y como ejecutarlas.

Para el caso se considera que se esta llevando a cabo un proyecto de investigación para determinar como los fabricantes de alimentos describen sus propiedades nutricionaless. Se han juntado datos acerca de 500 productos de un supermercado local, y se desea etiquetar cada uno de ellos de acuerdo a su densidad calórica y su contenido de azúcar y grasas.

Para eso, se desea etiquetar usando como criterio lo que la FDA (Food and Drug Administration) ha establecido para el país

| Category 	| Label        	| Criteria                                     	|
|----------	|--------------	|----------------------------------------------	|
| Calories 	| Calorie free 	| Less than 5 calories per serving             	|
| Calories 	| Low calorie  	| Less than 40 calories per serving            	|
| Fat      	| Fat free     	| Less than 0.5 grams of total fat per serving 	|
| Fat      	| Low fat      	| 3 grams or less of total fat per serving     	|
| Sugar    	| Sugar free   	| Less than 0.5 grams of sugar per serving     	|

Fuente: [American Diabetes Association](https://www.diabetes.org/healthy-living/recipes-nutrition/reading-food-labels) y [Institute of Medicine](https://www.ncbi.nlm.nih.gov/books/NBK209851/).

## Agregado de etiquetas calóricas

Cuando se escriben piezas extensas de código siempre es buena idea particionar las tareas en pequeñas unidad para hacerlo más manejable. Este es el árbol de decisión para las etiquetas calóricas:

![Calories tree](data/images/calories_tree.png)

Un ejemplo de código que se implementaría para este árbol de decisión e imprimir la etiqueta. Las características se toman de: ([US Department of Agriculture](https://fdc.nal.usda.gov/fdc-app.html#/food-details/362759/nutrients)):

~~~python
banana = {
    "serving_size":28, # In grams
    "calories":94.1, # In Kcal
    "fat":300, # In milligrams
    "sodium":1.96, # In milligrams
    "sugar":16, # In grams
    "fiber":0.504 # In grams
}
~~~

In [3]:
banana = {
    "serving_size":28,
    "calories":94.1,
    "fat":300,
    "sodium":1.96,
    "sugar":16,
    "fiber":0.504
}

if banana["calories"] < 5:
    calories_label = "CALORIE FREE"
elif banana["calories"] < 40:
    calories_label = "LOW CALORIE"
else:
    calories_label = None

print(calories_label)

None


Banana no tiene una etiqueta como tal porque tiene muchas calorias, por lo que no califica en `CALORIE FREE` o `LOW CALORIE`. Su etiqueta asignada es `None`.

### Ejercicio 1

Hacer lo mismo para el producto: [Tomate](https://fdc.nal.usda.gov/fdc-app.html#/food-details/1103276/nutrients):

~~~python
tomato = {
    "serving_size":125,
    "calories":22.5,
    "fat":250,
    "sodium":6.25,
    "sugar":3.29,
    "fiber":1.5
}
~~~

**Respuesta.**

In [4]:
tomato = {
    "serving_size":125,
    "calories":22.5,
    "fat":250,
    "sodium":6.25,
    "sugar":3.29,
    "fiber":1.5
}

if tomato["calories"] < 5:
    calories_label = "CALORIE FREE"
elif tomato["calories"] < 40:
    calories_label = "LOW CALORIE"
else:
    calories_label = None

print(calories_label)

LOW CALORIE


Debido a que un tomate (~125g) tiene más de 5 calorías y menos de 40, entonces es clasificado como `LOW CALORIE`.

Esta tarea se ha realizado para dos producto, ahora de pensar en más referencias sería un trabajo repetitivo y tedioso, por lo que es preciso a cudir a estrategias que faciliten estas tareas.

Las **funciones** resultan ser un trozo de código que puede ser usado de manera repetitiva con solo algunos ajustes en cualquier momento. Permiten generalizar tareas para aplicarlas en una gran variedad de situaciones. Para el código del ejemplo anterior:

~~~python
if banana["calories"] < 5:
    calories_label = "CALORIE FREE"
elif banana["calories"] < 40:
    calories_label = "LOW CALORIE"
else:
    calories_label = None

print(calories_label)
~~~

Esta tarea se podría generalizar si solo se realizara un cambio en el nombre del producto. Esto es posible con una función, así:

In [5]:
# Primera función

def assign_calories_label(food):
    if food["calories"] < 5: # Se cambia banana por food
        calories_label = "CALORIE FREE"
    elif food["calories"] < 40: # Se cambia banana por food
        calories_label = "LOW CALORIE"
    else:
        calories_label = None
    print(calories_label)

En el código de arriba se puede observar que se ha cambiado la palabra banana por food, de manera que sea más general. Adicionalmente, se ha agregado la línea 'def assign_calories_label(food):' que es donde def declara la función seguida por el nombre que recibirá la función y sus respectivos argumnetos (food).

Si esta función se ejecuta no va a regresarnos una salida en pantalla, lo que sucede es que la pieza de código queda almacenada dentro de la función y mostrará los resultados de su aplicación cuando se le pasen los debidos argumentos. Se destaca que el código al interior de la función está indentado

In [6]:
assign_calories_label(tomato)

LOW CALORIE


### Ejercicio 2

Test the `assign_calories_label()` function using `banana` instead.

**Respuesta**

In [7]:
assign_calories_label(banana)

None


Las funciones resultan ser útiles para generalizar tareas, sin embargo, quien construye la función es quien la conoce, por lo que es de suma importancia escribir documentación sobre lo que realiza la función, así otros usuarios podrán hacer uso de ella. La documentación se escribe al interior de la función haciendo uso de tres comillas ''', así:

In [8]:
def assign_calories_label(food):
    """
    Asigna una etiqueta calórica de acuerdo a las reglas de la FDA
    
    Arguments:
    food: Un diccionario en python que tiene al menos una clave "calories"
    
    Outputs:
    Esta función tan solo imprime la etiqueta.
    """
    if food["calories"] < 5:
        calories_label = "CALORIE FREE"
    elif food["calories"] < 40:
        calories_label = "LOW CALORIE"
    else:
        calories_label = None
    print(calories_label)
    return calories_label

### Ejercicio 3

¿Que sucede si se corre la línea:`help(assign_calories_label)`?

**Respuesta**

In [9]:
help(assign_calories_label)

Help on function assign_calories_label in module __main__:

assign_calories_label(food)
    Asigna una etiqueta calórica de acuerdo a las reglas de la FDA
    
    Arguments:
    food: Un diccionario en python que tiene al menos una clave "calories"
    
    Outputs:
    Esta función tan solo imprime la etiqueta.



La función completa aplicada a bananas y tomato y sus salidas son: 

In [10]:
tomato_calorie_label = assign_calories_label(tomato)
banana_calorie_label = assign_calories_label(banana)

LOW CALORIE
None


In [11]:
print("La etiqueta para tomate es: ", tomato_calorie_label)
print("Y la etiqueta para banana es: ", banana_calorie_label)

La etiqueta para tomate es:  LOW CALORIE
Y la etiqueta para banana es:  None


Este diagrama resume las diferentes partes de una función definida por el usuario en Python

![Def](data/images/def_anatomy.png)

## Agregar etiquetas para grasas

Ahora que ya se cuenta con una función para etiquetal las calorías se hará lo mismo para el contenido de grasas. Este es el árbol de decisión

![Fat decision tree](data/images/fat_tree.png)

### Ejercicio 4

Crear la función `assign_fat_label()` para implentar el árbol de decisión 

**Respuesta**

In [12]:
def assign_fat_label(food):
    """
    Asigna una etiqueta de grasa de acuerdo a las reglas de la FDA
    
    Arguments:
    food: Un diccionario en python que tiene al menos una clave "fat"
    
    Outputs:
    Esta función tan solo imprime la etiqueta.
    """
    
    if food["fat"] < 0.5:
        fat_label = "FAT FREE"
    elif food["fat"] < 3:
        fat_label = "LOW FAT"
    else:
        fat_label = None
    return fat_label

Probando esta función con `tomato` tendría como salida:

In [13]:
print(assign_fat_label(tomato))

None


Sorpresivamente el tomate no tiene etiqueta, se esperaba que fuera `FAT FREE`. ¿Que pasó?

In [14]:
tomato

{'serving_size': 125,
 'calories': 22.5,
 'fat': 250,
 'sodium': 6.25,
 'sugar': 3.29,
 'fiber': 1.5}

Al parecer el problema está en las unidades. Si en promedio un tomate pesa 125 gr, no es posible que tenga 250 gramos de grasa, más bien deben ser miligramos. La modificación de unidades pueder ser incluida fácilmente dentro de la función previamente definida

### Ejercicio 5

Modificar la función `assign_fat_label()` para convertir los miligramos a gramos

**Respuesta.**

In [15]:
def assign_fat_label(food):
    """
    Asigna una etiqueta de grasa de acuerdo a las reglas de la FDA
    
    Argumentos:
    food: Un diccionario en python que tiene al menos una clave "fat"
    El valor de 'fat' debe estar en miligramos
    
    Outputs:
    Esta función tan solo imprime la etiqueta.
    """
    
    if food["fat"] / 1000 < 0.5:
            fat_label = "FAT FREE"
    elif food["fat"] / 1000 < 3:
        fat_label = "LOW FAT"
    else:
        fat_label = None
    return fat_label

Probando la función modificada:

In [16]:
print(assign_fat_label(tomato))

FAT FREE


## Agregar etiquetas al azúcar

Para el azúcar, la tarea es más sencilla. Si hay menos de 0.5 gr de azúcar se dice que es `SUGAR FREE`, de lo contrario no se le asigna etiqueta.

In [17]:
def assign_sugar_label(food):
    """
    Asigna una etiqueta de azúcar de acuerdo a las reglas de la FDA
    
    Argumentos:
    food: Un diccionario en python que tiene al menos una clave "sugar"
    
    Outputs:
    Esta función tan solo imprime la etiqueta.
    """
    
    if food["sugar"] < 0.5:
        sugar_label = "SUGAR FREE"
    else:
        sugar_label = None
    return sugar_label

Para evidenciar que nuestra función trabaja de manera correcta se hace la prueba con banana, que claramente no es libre de azúcar

In [18]:
print(assign_sugar_label(banana))

None


## Juntar todo

### Ejercicio 6

Piense en una estrategia para incluir esas tres funciones en una sola evitando escribir código redundante. No escriba nuevo código, utilice las funciones ya creadas

**Respuesta.**

In [20]:
def assign_fda_labels(food):
    """
    
    Asigna etiquetas según la FDA para calorías, grasa y azúcar
    
    Argumentos:
    food: Un diccionario en python que tiene al menos una clave "sugar", "calories" and "fat".
    
    Output:
    Esta función tan solo imprime la etiqueta.
    """
    
    calories_label = assign_calories_label(food)
    fat_label = assign_fat_label(food)
    sugar_label = assign_sugar_label(food)
    
    labels = [calories_label, fat_label, sugar_label]
    return labels

## Funciones anónimas

Por lo general se tienen funciones que no serán utilizadas solo una vez, por lo que se desearía no definirla sino darle un único uso. Para este caso existen funciones anónimas que tan solo sustituyen  el "`def`" por **`lambda`** y no es necesario darle nombre a la función, al fin y al cabo solo se utilizará una vez.

~~~python
lambda mi_input: <Hacer algo con mi_input> # Se puede poner más de un input separados por coma
~~~

Entonces, para evaluar la función, usamos:

~~~python
(lambda mi_input: <Hacer algo con mi_input>)(Input actual)
~~~

La versión anónima de nuestra función `assign_fda_labels(food)` podría ser:

~~~python
lambda food: [assign_calories_label(food), assign_fat_label(food), assign_sugar_label(food)]
~~~

In [19]:
(lambda food: [assign_calories_label(food), assign_fat_label(food), assign_sugar_label(food)])(banana)

None


[None, 'FAT FREE', None]